"""Markdown report writer.

Produces a human-readable Markdown report from AnalysisReport.
Sections follow the 9 questions from the product spec.
"""

from __future__ import annotations

from enum import Enum
from pathlib import Path

from pointer.models import AnalysisReport, Evidence


def to_markdown(report: AnalysisReport) -> str:
    """Generate a full Markdown report."""
    lines: list[str] = []

    # Header
    lines.append("# Pointer Portability Report")
    lines.append("")
    lines.append("| Field | Value |")
    lines.append("|-------|-------|")
    lines.append(f"| **Schema version** | `{report.schema_version}` |")
    lines.append(f"| **Pointer version** | `{report.pointer_version}` |")
    lines.append(f"| **Analysis target** | `{report.target}` |")
    lines.append(f"| **Timestamp** | {report.analysis_timestamp} |")
    lines.append(f"| **Repository** | `{report.root_path}` |")
    lines.append("")

    # Summary
    if report.summary:
        lines.append("## Summary")
        lines.append("")
        lines.append(report.summary)
        lines.append("")

    # Warnings and errors
    if report.warnings:
        lines.append("## Warnings")
        lines.append("")
        for w in report.warnings:
            lines.append(f"- ⚠️ {w}")
        lines.append("")

    if report.errors:
        lines.append("## Errors")
        lines.append("")
        for e in report.errors:
            lines.append(f"- ❌ {e}")
        lines.append("")

    # Q1: What kind of Python repository is this?
    _section_repository_type(lines, report)
    # Q2: Packaging/build systems, lockfiles, source roots, entry points, test layout
    _section_packaging(lines, report)
    # Q3: Pure Python or partly native?
    _section_native_status(lines, report)
    # Q4: Imports/dependencies/native-extension signals
    _section_imports_and_deps(lines, report)
    # Q5: Dynamic constructs that make porting difficult
    _section_dynamic_blockers(lines, report)
    # Q6: Test/oracle evidence
    _section_test_evidence(lines, report)
    # Q7: Migration seams/order
    _section_migration_seams(lines, report)
    # Q8: Rust vs C++ recommendation
    _section_recommendation(lines, report)
    # Q9: Known, inferred, and unknown
    _section_evidence_taxonomy(lines, report)

    # Footer
    lines.append("---")
    lines.append("")
    lines.append(
        "*Generated by [Pointer](https://github.com/pilkquant/pointer) — "
        "a static Python portability analyzer. "
        "All findings are based on static analysis signals and should be verified "
        "before making porting decisions.*"
    )

    return "\n".join(lines)


def _section_repository_type(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 1. Repository Profile")
    lines.append("")

    struct = report.structure
    if struct is None:
        lines.append("No project structure data available.")
        lines.append("")
        return

    if struct.project_name:
        lines.append(f"**Project name**: `{struct.project_name}`")
    if struct.version:
        lines.append(f"**Version**: `{struct.version}`")
    if struct.requires_python:
        lines.append(f"**Requires Python**: `{struct.requires_python}`")
    lines.append("")

    lines.append(f"**Python files**: {report.metrics.total_py_files if report.metrics else '?'}")
    if report.metrics:
        lines.append(f"**Total Python lines**: {report.metrics.total_py_lines}")
        lines.append(f"**Logical lines (non-blank/comment)**: {report.metrics.total_py_logical_lines}")
        lines.append(f"**Modules** (packages with `__init__.py`): {report.metrics.module_count}")
    lines.append("")

    if struct.build_systems:
        build_names = ", ".join(f"`{b.name}`" for b in struct.build_systems)
        lines.append(f"**Build system(s)**: {build_names}")
    else:
        lines.append("**Build system(s)**: None detected (no `pyproject.toml`, `setup.py`, or `setup.cfg`).")
    lines.append("")


def _section_packaging(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 2. Packaging & Project Layout")
    lines.append("")

    struct = report.structure
    if struct is None:
        lines.append("No packaging data available.")
        lines.append("")
        return

    # Build systems
    if struct.build_systems:
        lines.append("### Build Systems")
        lines.append("")
        lines.append("| System | Backend | Evidence |")
        lines.append("|--------|---------|----------|")
        for b in struct.build_systems:
            lines.append(f"| `{b.name}` | `{b.backend or '—'}` | {b.evidence.value} |")
        lines.append("")

    # Lockfiles
    if struct.lockfiles:
        lines.append("### Lockfiles")
        lines.append("")
        lines.append("| File | Type |")
        lines.append("|------|------|")
        for lf in struct.lockfiles:
            lines.append(f"| `{lf.path}` | {lf.kind} |")
        lines.append("")

    # Source roots
    if struct.source_roots:
        lines.append("### Source Roots")
        lines.append("")
        for sr in struct.source_roots:
            pkgs = ", ".join(f"`{p}`" for p in sr.package_names) if sr.package_names else "*(none found)*"
            lines.append(f"- **`{sr.path}`** — packages: {pkgs}")
        lines.append("")

    # Entry points
    if struct.entry_points:
        lines.append("### Entry Points")
        lines.append("")
        lines.append("| Name | Module | Attribute | Group |")
        lines.append("|------|--------|-----------|-------|")
        for ep in struct.entry_points:
            lines.append(f"| `{ep.name}` | `{ep.module}` | `{ep.attr or '—'}` | {ep.group} |")
        lines.append("")

    # Declared dependencies
    if struct.dependencies:
        lines.append("### Declared Dependencies")
        lines.append("")
        for dep in struct.dependencies:
            lines.append(f"- `{dep}`")
        lines.append("")


def _section_native_status(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 3. Native Extension Status")
    lines.append("")

    ne = report.native_ext
    if ne is None:
        lines.append("No native extension data available.")
        lines.append("")
        return

    if ne.has_native_extensions:
        lines.append("**This project has native extension signals.**")
        lines.append("")
        lines.append("The following signals were detected:")
        lines.append("")
        for signal in ne.signals:
            ev_label = "🔍" if signal.evidence == Evidence.OBSERVED else "💡"
            file_info = f" (`{signal.file}`)" if signal.file else ""
            lines.append(f"- {ev_label} **{signal.kind}**: {signal.detail}{file_info}")
        lines.append("")
    else:
        lines.append("**This appears to be a pure-Python project.**")
        lines.append("")
        lines.append("No compiled extensions, native build backends, or binding tool references were detected.")
        lines.append("")

    if ne.binding_tools:
        lines.append(f"**Binding tools detected**: {', '.join(f'`{b}`' for b in ne.binding_tools)}")
        lines.append("")


def _section_imports_and_deps(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 4. Imports & Dependencies")
    lines.append("")

    ast_data = report.ast_analysis
    if ast_data is None:
        lines.append("No import data available.")
        lines.append("")
        return

    lines.append(f"**Total Python files scanned**: {ast_data.total_py_files}")
    lines.append("")

    if ast_data.external_imports:
        lines.append("### External Imports")
        lines.append("")
        lines.append("Non-stdlib modules imported by the project:")
        lines.append("")
        for imp in ast_data.external_imports:
            lines.append(f"- `{imp}`")
        lines.append("")

    if ast_data.stdlib_imports:
        lines.append("### Standard Library Imports")
        lines.append("")
        lines.append(f"*({len(ast_data.stdlib_imports)} stdlib modules used)*")
        lines.append("")
        # Show first 20
        for imp in ast_data.stdlib_imports[:20]:
            lines.append(f"- `{imp}`")
        if len(ast_data.stdlib_imports) > 20:
            lines.append(f"- *...and {len(ast_data.stdlib_imports) - 20} more*")
        lines.append("")

    # Dependency dispositions
    if report.dependency_dispositions:
        lines.append("### Dependency Portability Disposition")
        lines.append("")
        lines.append("| Package | Disposition | Confidence | Rust | C++ |")
        lines.append("|---------|-------------|------------|------|-----|")
        for dep in report.dependency_dispositions:
            rust_short = dep.rust_notes[:80] + ("..." if len(dep.rust_notes) > 80 else "") if dep.rust_notes else "—"
            cpp_short = dep.cpp_notes[:80] + ("..." if len(dep.cpp_notes) > 80 else "") if dep.cpp_notes else "—"
            lines.append(
                f"| `{dep.name}` | `{dep.disposition}` | {dep.confidence.value} | {rust_short} | {cpp_short} |"
            )
        lines.append("")
        lines.append("*Provenance details available in report.json*")
        lines.append("")


def _section_dynamic_blockers(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 5. Dynamic Language Blockers")
    lines.append("")

    ast_data = report.ast_analysis
    if ast_data is None or not ast_data.dynamic_blockers:
        lines.append("**No significant dynamic language blockers detected.**")
        lines.append("")
        lines.append(
            "The codebase avoids eval/exec, metaclasses, and monkeypatching, "
            "which makes it more amenable to native porting."
        )
        lines.append("")
        return

    blockers = ast_data.dynamic_blockers
    high = [b for b in blockers if b.severity == "high"]
    medium = [b for b in blockers if b.severity == "medium"]
    low = [b for b in blockers if b.severity == "low"]

    lines.append(
        f"**{len(blockers)} dynamic constructs detected** "
        f"({len(high)} high, {len(medium)} medium, {len(low)} low severity)"
    )
    lines.append("")

    if high:
        lines.append("### High Severity")
        lines.append("")
        for b in high[:20]:
            lines.append(f"- 🔴 **{b.category}** at `{b.file}:{b.line}` — {b.description}")
            if b.snippet:
                lines.append("  ```python")
                lines.append(f"  {b.snippet}")
                lines.append("  ```")
        if len(high) > 20:
            lines.append(f"- *...and {len(high) - 20} more*")
        lines.append("")

    if medium:
        lines.append("### Medium Severity")
        lines.append("")
        for b in medium[:15]:
            lines.append(f"- 🟡 **{b.category}** at `{b.file}:{b.line}` — {b.description}")
        if len(medium) > 15:
            lines.append(f"- *...and {len(medium) - 15} more*")
        lines.append("")

    if low:
        lines.append("### Low Severity")
        lines.append("")
        for b in low[:10]:
            lines.append(f"- 🟢 **{b.category}** at `{b.file}:{b.line}` — {b.description}")
        if len(low) > 10:
            lines.append(f"- *...and {len(low) - 10} more*")
        lines.append("")


def _section_test_evidence(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 6. Test & Oracle Evidence")
    lines.append("")

    tests = report.tests
    if tests is None:
        lines.append("No test data available.")
        lines.append("")
        return

    lines.append(f"**Test files**: {len(tests.test_files)}")
    test_dirs = ", ".join(f"`{d}`" for d in tests.test_dirs) if tests.test_dirs else "*(none)*"
    lines.append(f"**Test directories**: {test_dirs}")
    frameworks = ", ".join(tests.frameworks_detected) if tests.frameworks_detected else "*(none)*"
    lines.append(f"**Frameworks detected**: {frameworks}")
    lines.append(f"**Has conftest.py**: {'Yes' if tests.has_conftest else 'No'}")
    lines.append(f"**Has fixtures**: {'Yes' if tests.has_fixtures else 'No'}")
    lines.append("")

    # Oracle readiness
    readiness_emoji = {"high": "🟢", "medium": "🟡", "low": "🔴", "unknown": "❓"}
    emoji = readiness_emoji.get(tests.oracle_readiness, "❓")
    lines.append(f"### Oracle Readiness: {emoji} {tests.oracle_readiness.title()}")
    lines.append("")
    lines.append(tests.oracle_readiness_reason)
    lines.append("")

    if tests.test_files:
        lines.append("### Test Files")
        lines.append("")
        lines.append("| File | Framework |")
        lines.append("|------|-----------|")
        for tf in tests.test_files[:30]:
            lines.append(f"| `{tf.path}` | {tf.framework} |")
        if len(tests.test_files) > 30:
            lines.append(f"| *...and {len(tests.test_files) - 30} more* | |")
        lines.append("")


def _section_migration_seams(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 7. Migration Seams & Ordering")
    lines.append("")

    if not report.migration_seams:
        lines.append("No migration seams suggested — insufficient module/dependency data for analysis.")
        lines.append("")
        return

    lines.append(
        "*These are recommendations based on module boundaries "
        "and dependency concentration, not definitive porting orders.*"
    )
    lines.append("")

    priority_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}
    for seam in report.migration_seams:
        emoji = priority_emoji.get(seam.priority, "❓")
        lines.append(f"### {emoji} `{seam.module}` (priority: {seam.priority})")
        lines.append(f"**Reason**: {seam.reason}")
        if seam.dependencies:
            lines.append(f"**Key dependencies**: {', '.join(f'`{d}`' for d in seam.dependencies[:5])}")
        if seam.blockers:
            lines.append(f"**Blockers**: {', '.join(f'`{b}`' for b in seam.blockers)}")
        lines.append("")


def _section_recommendation(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 8. Target Recommendation")
    lines.append("")

    rec = report.recommendation
    if rec is None:
        lines.append("No recommendation available.")
        lines.append("")
        return

    target_display = {
        "rust": "🦀 Rust",
        "cpp": "🔧 C++",
        "hybrid": "🔀 Hybrid (Python + Native)",
        "stay_python": "🐍 Stay in Python",
        "inconclusive": "❓ Inconclusive",
    }
    display = target_display.get(rec.target, rec.target)
    conf_emoji = {"high": "🟢", "medium": "🟡", "low": "🔴"}
    conf_value = rec.confidence.value if isinstance(rec.confidence, Enum) else rec.confidence
    conf_label = conf_emoji.get(conf_value, "❓")

    lines.append(f"### Recommendation: {display} (confidence: {conf_label} {conf_value})")
    lines.append("")

    lines.append(rec.rationale)
    lines.append("")

    lines.append("### Scoring")
    lines.append("")
    lines.append("| Factor | Base | Rust adj. | C++ adj. | Reason |")
    lines.append("|--------|------|----------|----------|--------|")
    for f in rec.factors:
        lines.append(f"| {f.name} | {f.score:+d} | {f.rust_weight:+d} | {f.cpp_weight:+d} | {f.reason} |")
    lines.append(f"| **Total** | | **{rec.rust_score:+d}** | **{rec.cpp_score:+d}** | |")
    lines.append(f"| **Stay-Python score** | **{rec.stay_python_score:+d}** | | | |")
    lines.append("")

    lines.append("### Caveats")
    lines.append("")
    for caveat in rec.caveats:
        lines.append(f"- ⚠️ {caveat}")
    lines.append("")


def _section_evidence_taxonomy(lines: list[str], report: AnalysisReport) -> None:
    lines.append("## 9. Evidence, Inference & Unknowns")
    lines.append("")

    lines.append("Pointer distinguishes between three types of findings:")
    lines.append("")
    lines.append(
        "- **Observed** 🔍: directly detected in the repository "
        "(e.g., a `.so` file exists, a `pyproject.toml` declares `maturin`)"
    )
    lines.append(
        "- **Inferred** 💡: deduced from signals (e.g., a module name suggests a dependency, code size suggests effort)"
    )
    lines.append("- **Unknown** ❓: insufficient data to make a determination")
    lines.append("")

    ast_data = report.ast_analysis
    if ast_data:
        if ast_data.files_with_syntax_errors:
            lines.append("### Files with Syntax Errors")
            lines.append("")
            lines.append("These files could not be parsed and may contain incomplete or invalid Python:")
            lines.append("")
            for err in ast_data.files_with_syntax_errors:
                lines.append(f"- `{err}`")
            lines.append("")

    struct = report.structure
    if struct and struct.errors:
        lines.append("### Parse Errors")
        lines.append("")
        for err in struct.errors:
            lines.append(f"- `{err}`")
        lines.append("")

    # Unknown dependencies
    unknown_deps = [d for d in report.dependency_dispositions if d.disposition == "unknown"]
    if unknown_deps:
        lines.append("### Unknown Dependencies")
        lines.append("")
        lines.append(
            "These dependencies are not in Pointer's curated knowledge base. "
            "Manual research is required before making porting decisions:"
        )
        lines.append("")
        for dep in unknown_deps:
            lines.append(f"- `{dep.name}`")
        lines.append("")

    lines.append("### Type Annotation Coverage")
    lines.append("")
    if ast_data and ast_data.type_annotation_coverage is not None:
        pct = ast_data.type_annotation_coverage
        if pct > 0:
            lines.append(f"{pct:.0%} of functions have type annotations.")
        else:
            lines.append("No type annotations detected.")
    else:
        lines.append("Not measured (no Python functions found).")
    lines.append("")


def write_markdown(report: AnalysisReport, output_dir: Path) -> Path:
    """Write report.md to the output directory. Returns the file path."""
    output_dir.mkdir(parents=True, exist_ok=True)
    filepath = output_dir / "report.md"
    filepath.write_text(to_markdown(report) + "\n", encoding="utf-8")
    return filepath
